### ISSUE TITLE
Project description and Linux build instructions

### ISSUE THREAD

**Issue by danboid** [FigBug/SID#1]
I'm very keen to test this plugin but when I try using the binary version downloaded from the Tracktion site, there is no text displayed in the plugins UI under both Ardour (5.11) and the latest test version of REAPER running under Ubuntu MATE 17.10 x64.

I decided the next course of action would be try building this plugin from source although I'm not sure how to do that. I installed the personal/free version of projucer  but the 'Build now' option is greyed out so I'm not sure if that is even available in the personal edition?

I have also tried just running `make`:

```
:~/src/SID/plugin/Builds/LinuxMakefile$ make
Compiling include_juce_audio_plugin_client_VST2.cpp
../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp:9:10: fatal error: juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp: No such file or directory
 #include <juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:152: recipe for target 'build/intermediate/Debug/include_juce_audio_plugin_client_VST2_dd551e08.o' failed
make: *** [build/intermediate/Debug/include_juce_audio_plugin_client_VST2_dd551e08.o] Error 1
```

Please could you add a README.md file to the root of this github repo that briefly explains what the project is and how to build it under (Ubuntu) Linux.

Thanks

**Comment by FigBug** [comment]
The font it's looking for is Verdana, which I though most Linux distros should include

To build, clone SID including submodules to a directory
clone JUCE to that same directory

I should make JUCE  submodule so it just works

**Comment by danboid** [comment]
Hi Roland

I've made some progress. I've got Verdana installed now and as a result the UI is dsplayed properly when using the Tracktion binary BUT users of recent versions of Ubuntu cannot install msttcorefonts from the package manager in the usual way due to a known bug in said package. The solution at present is to run:

```
wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
sudo dpkg -i ttf-mscorefonts-installer_3.6_all.deb
```

Here is the Ubuntu bug report, which also effects 17.10:

https://bugs.launchpad.net/ubuntu/+source/msttcorefonts/+bug/1607535

I've got further with building the plugin although it still doesn't fully build. These are my presumed build instructions from what you've hinted at:

```
git clone https://github.com/FigBug/SID.git
git clone https://github.com/WeAreROLI/JUCE.git
cd SID/plugin/Builds/LinuxMakefile/
make
```

Which produces:

```
$ make
Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling envelope.cc
Compiling extfilt.cc
Compiling filter.cc
Compiling pot.cc
Compiling sid.cc
Compiling version.cc
Compiling voice.cc
Compiling wave.cc
Compiling wave6581__ST.cc
Compiling wave6581_P_T.cc
Compiling wave6581_PS_.cc
Compiling wave6581_PST.cc
Compiling wave8580__ST.cc
Compiling wave8580_P_T.cc
Compiling wave8580_PS_.cc
Compiling wave8580_PST.cc
make: *** No rule to make target '../../../modules/slCommon/slComponents.cpp', needed by 'build/intermediate/Debug/slComponents_3caabb18.o'. Stop.
```

**Comment by FigBug** [comment]
Try

cd SID
git submodule update --init --recursive

**Comment by danboid** [comment]
:~/src/SID/plugin/Builds/LinuxMakefile$ git submodule update --init --recursive
Submodule 'modules/dRowAudio' (git@github.com:FigBug/drowaudio.git) registered for path '../../../modules/dRowAudio'
Submodule 'modules/slCommon' (git@github.com:FigBug/slCommon.git) registered for path '../../../modules/slCommon'
Cloning into '/home/dan/src/SID/modules/dRowAudio'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/drowaudio.git' into submodule path '/home/dan/src/SID/modules/dRowAudio' failed
Failed to clone 'modules/dRowAudio'. Retry scheduled
Cloning into '/home/dan/src/SID/modules/slCommon'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/slCommon.git' into submodule path '/home/dan/src/SID/modules/slCommon' failed
Failed to clone 'modules/slCommon'. Retry scheduled
Cloning into '/home/dan/src/SID/modules/dRowAudio'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/drowaudio.git' into submodule path '/home/dan/src/SID/modules/dRowAudio' failed
Failed to clone 'modules/dRowAudio' a second time, aborting

**Comment by danboid** [comment]
~/src/SID$ git submodule update --init --recursive
Cloning into '/home/dan/src/SID/modules/dRowAudio'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/drowaudio.git' into submodule path '/home/dan/src/SID/modules/dRowAudio' failed
Failed to clone 'modules/dRowAudio'. Retry scheduled
Cloning into '/home/dan/src/SID/modules/slCommon'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/slCommon.git' into submodule path '/home/dan/src/SID/modules/slCommon' failed
Failed to clone 'modules/slCommon'. Retry scheduled
Cloning into '/home/dan/src/SID/modules/dRowAudio'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FigBug/drowaudio.git' into submodule path '/home/dan/src/SID/modules/dRowAudio' failed
Failed to clone 'modules/dRowAudio' a second time, aborting

**Comment by FigBug** [comment]
Do you have you ssh keys setup for GitHub or do you usually clone via http?

**Comment by FigBug** [comment]
https://help.github.com/articles/error-permission-denied-publickey/ <https://help.github.com/articles/error-permission-denied-publickey/>

**Comment by danboid** [comment]
Hi Roland

I shoud've known it was just a case of registering my SSH key with github from those errors so after doing that I have now got SID building under Ubuntu 17.10! Thanks!

Hence, some provisional (at least) Linux build instructions would read like so:

## Building under Linux

**NOTE:** Before you can clone all of the required repos to build this plugin, you need to ensure your SSH keys are correctly registered with your github account. Building requires you have the mesa dev packages for your distro installed, amongst others.

[Add SSH keys to github](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)

```
git clone https://github.com/WeAreROLI/JUCE.git
git clone https://github.com/FigBug/SID.git
cd SID
git submodule update --init --recursive
cd plugin/Builds/LinuxMakefile/
make
```

**Comment by simonvanderveldt** [comment]
FYI the submodules should just use the HTTPS URL instead of SSH so anyone can clone it even if they don't have SSH keys setup

**Comment by cyberic99** [comment]
To change the submodules repo to HTTPS ones, edit your SID/.gitmodules like this:
```
[submodule "modules/dRowAudio"]
	path = modules/dRowAudio
	url = https://github.com/FigBug/drowaudio.git
[submodule "modules/slCommon"]
	path = modules/slCommon
	url = https://github.com/FigBug/slCommon.git
```

**Comment by mxmilkiib** [comment]
What build steps changed recently? The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sid-vst-git) in AUR currently fails. I might as well ask to save time and so others with different distros can build sucsesfully. Thanks.

**Comment by FigBug** [comment]
Arg, this is going to be a pain.

Steinberg recently cracked down on people distributing the VST2 SDK, so
juce removed it from their repo. However, VST3 doesn't work on Linux yet
(as of last time I checked). They also don't grant licenses for VST2
anymore.

I don't really want to add VST2 to my repo and get hit with a DMCA takedown.

Not really sure how to handle this going forward

**Comment by jpcima** [comment]
The GPL-based VST2 support was removed after Juce 5.3.2.
This is worked around using the same way as Debian buster did: backport 5.3.2 bits into the newer version.

This source package has it (juce_5.4.1+really5.4.1~repack-3.debian.tar.xz)
https://packages.debian.org/buster/juce-modules-source

1. apply `patches/debian_vst.patch`
2. copy `extra/juce_audio_processors/format_types/juce_VSTInterface.h`

**Comment by FigBug** [comment]
ok, should build again now. Added another submodule.

**Comment by mxmilkiib** [comment]
N.b. I don't have the time or energy atm to resolve the PKGBUILD issue so I have disowned it on AUR to allow someone else who is interested and available to do so to step in.
