### ISSUE TITLE
Missing font on Ubuntu / Reaper

### ISSUE THREAD

**Issue by alexandrevicenzi** [FigBug/SID#11]
Hi,

SID, PAPU, and others have no text on Reaper 6.19 / Ubuntu 20.

Ubuntu:

![image](https://user-images.githubusercontent.com/2637672/103369607-e32a9500-4aca-11eb-826f-99688ec504df.png)

Windows 10:

![image](https://user-images.githubusercontent.com/2637672/103369740-369ce300-4acb-11eb-9156-be22cda45dd3.png)

Looking over JUCE code, there are many fonts that it tries to find and use, most are available on Ubuntu. I'm not really sure where the problem could be, my first thought was missing fonts, but it could be something else.

If the issue is in JUCE I can submit this to JUCE.

**Comment by FigBug** [comment]
You need to install the microsoft fonts. I should really change it to use a font that is installed by default.

`sudo apt update && sudo apt install ttf-mscorefonts-installer`

**Comment by alexandrevicenzi** [comment]
Thanks for quick response. It worked. Feel free to close this issue.
